# Generated by Django 5.1.2 on 2024-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('nombre_de_chambres', models.IntegerField()),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
